name: Create Mission Enclave Sentinel terraform plan

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SECURITY_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}   
      ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform plan
        id: plan
        uses: azurenoops/terraform-github-actions/terraform-plan@v1.34.2
        with:
          path: infrastructure/terraform
          variables: |
            security_subscription_id           = "${{ env.ARM_SUBSCRIPTION_ID }}"          
          var_file: |
            infrastructure/terraform/tfvars/parameters.tfvars
          backend_config: |
            storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.TFSTATE_RG }}
       
      - name: 'Upload Sentinel Plan Artifact'
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}.tfplan
          path: ${{ steps.plan.outputs.json_plan_path }}
          retention-days: 5

  